apiVersion: v1
kind: Template
metadata:
  name: eclipse-guestbook-app
  annotations:
    description: "Template used for the guestbook app"
    iconClass: "icon-php"
    tags: "app"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: frontend
    labels:
      app: guestbook
      name: guestbook
  spec:
    ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
    selector:
      app: guestbook
    type: LoadBalancer
- apiVersion: v1
  kind: ImageStream
  metadata: 
    name: sample-frontend 
    annotations: 
      description: Keeps track of changes in the application image
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: sample-frontend
    annotations: 
      description: Defines how to build the application
  spec: 
    source: 
      type: Git
      git: 
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${CONTEXT_DIR}"
    strategy: 
      type: Docker
      dockerStrategy: 
        "forcePull": true
    output: 
      pushSecret: 
        name: dockerhub
      to: 
        kind: ImageStreamTag
        name: sample-frontend:latest
    triggers: 
      - type: ImageChange
      - type: ConfigChange
      - type: GitHub
        github: 
          secret: "${GITHUB_WEBHOOK_SECRET}"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: frontend
  spec:
    triggers: 
      - type: ImageChange
        imageChangeParams: 
          automatic: true
          containerNames: 
            - guestbook
          from: 
            kind: ImageStreamTag
            name: sample-frontend:latest
      - type: ConfigChange
    replicas: 3
    template:
      metadata:
        labels:
          app: guestbook
          name: frontend
          uses: redis
      spec:
        containers:
        - name: guestbook
          image: sample-frontend:latest
          ports:
          - name: http-server
            containerPort: 80
        imagePullSecrets:
        - name: dockerhub
- apiVersion: v1
  kind: Service
  metadata:
    name: redis-master
    labels:
      role: master
  spec:
    ports:
      # the port that this service should serve on
    - port: 6379
      targetPort: 6379
    selector:
      role: master
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: redis-master
    labels:
      app: redis
      role: master
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: redis
          role: master
          name: redis
      spec:
        containers:
        - name: redis-master
          image: redis  # or just image: redis
          ports:
          - containerPort: 6379
            name: redis-master
- apiVersion: v1
  kind: Service
  metadata:
    name: redis-slave
    labels:
      name: redis
      role: slave
  spec:
    ports:
    # the port that this service should serve on
    - port: 6379
      targetPort: 6379
    selector:
      role: slave
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: redis-slave
  # these labels can be applied automatically
  # from the labels in the pod template if not set
    labels:
     app: redis
     role: slave
     name: redis
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: redis
          role: slave
          name: redis
      spec:
        containers:
        - name: redis-slave
          image: kubernetes/redis-slave:v2
          ports:
          - containerPort: 6379
            name: redis-server
parameters: 
  - name: NAME
    displayName: Name
    description: The name assigned to all of the frontend objects defined in this template
    required: true
    value: cakephp-mysql-example
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code
    required: true
    value: https://github.com/madhukar32/sample-guestbook-frontend.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  - name: CONTEXT_DIR
    displayName: Context Directory
    description: Set this to the relative path to your project if it is not in the root of your repository
  - name: GITHUB_WEBHOOK_SECRET
    displayName: GitHub Webhook Secret
    description: A secret string used to configure the GitHub webhook
    generate: expression
    from: "[a-zA-Z0-9]{40}"
